config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount_roboto
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  root 'pages#home'

  resources :users do
    member do
      patch 'activate'
      patch 'suspend'
    end
  end

  resources :posts
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :posts, only: %i[index]
    end
    namespace :api, default: { format: :json } do
      resources :posts
    end
  end

  resources :about_items, only: %i[index new edit create update destroy] do
    member do
      patch 'move_first'
      patch 'move_previous'
      patch 'move_next'
      patch 'move_last'
    end
  end
  get 'about', to: 'about_items#index'

  resources :histories, param: :generation_code do
    resources :activities, only: %i[index new edit create update destroy]
    resources :upload_files, only: %i[index new edit create update destroy] do
      member do
        post 'download'
      end
    end
  end

  resources :supporters, only: %i[index new edit create update destroy] do
    member do
      patch 'move_first'
      patch 'move_previous'
      patch 'move_next'
      patch 'move_last'
    end
  end

  resources :questions, only: %i[index new edit create update destroy]
  get 'faq', to: 'questions#index'

  resources :faq_categories, only: %i[index new edit create update destroy]

  resources :contacts, only: %i[new create]
  get 'contact', to: 'contacts#new'

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/models/faq_category.rb
# == Schema Information
#
# Table name: faq_categories
#
#  id         :bigint(8)        not null, primary key
#  category   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FaqCategory < ApplicationRecord
  has_many :questions, dependent: :destroy
  validates :category, presence: true
end

app/controllers/faq_categories_controller.rb
class FaqCategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_faq_category, only: %i[update destroy]
  load_and_authorize_resource
  add_breadcrumb "#{FaqCategory.model_name.human}#{I18n.t('misc.index')}", :faq_categories_path
  # GET /faq_categories
  def index
    @q = FaqCategory.all.ransack(params[:q])
    @faq_categories = @q.result.page(params[:page])
  end

  # GET /faq_categories/new
  def new
    @faq_category = FaqCategory.new
  end

  # GET /faq_categories/:id/edit
  def edit
  end

  # POST /faq_categories
  def create
    @faq_category = FaqCategory.new(faq_category_params)
    if @faq_category.errors.empty? && @faq_category.save
      redirect_to faq_categories_path, notice: I18n.t('activerecord.flash.faq_category.actions.create.success')
    else
      render :new, alert: I18n.t('activerecord.flash.faq_category.actions.create.failure')
    end
  end

  # PATCH/PUT /faq_categories/:id
  def update
    if @faq_category.errors.empty? && @faq_category.update(faq_category_params)
      redirect_to faq_categories_path, notice: I18n.t('activerecord.flash.faq_category.actions.update.success')
    else
      render :edit, alert: I18n.t('activerecord.flash.faq_category.actions.update.failure')
    end
  end

  # DELETE /faq_categories/:id
  def destroy
    if @faq_category.destroy
      redirect_to faq_categories_path, notice: I18n.t('activerecord.flash.faq_category.actions.destroy.success')
    else
      redirect_to faq_categories_path, alert: I18n.t('activerecord.flash.faq_category.actions.destroy.failure')
    end
  end

  private

  def faq_category_params
    params.require(:faq_category).permit(:category)
  end

  def set_faq_category
    @faq_category = FaqCategory.find(params[:id])
  end
end

app/views/faq_categories/_form.html.slim
.has-text-centered
  .column.is-4.is-offset-4
    - if @faq_category.errors.any?
      - @faq_category.errors.full_messages.each do |message|
        .notification.is-danger
          = message

= form_with(model: @faq_category, local: true, class: 'control') do |f|
  .field.is-horizontal
    .field-label= f.label :category, class: 'label'
    .field-body
      .field
        p.control= f.text_field :category, class: 'input'

  .field.is-horizontal
    .field-label
    .field-body
      .field
        .control.is-pulled-right= f.submit nil, class: 'button is-primary'

app/views/faq_categories/_results.html.slim
.section
  .field.is-pulled-right
    = page_entries_info @faq_categories
.section
  .field.is-pulled-right
    = paginate @faq_categories

table.table.is-fullwidth.is-striped
  thead
    tr
      th= FaqCategory.human_attribute_name :id
      th= FaqCategory.human_attribute_name :category
      th

  tbody
    - @faq_categories.each do |faq_category|
      tr
        td= faq_category.id
        td= faq_category.category
        td
          .dropdown.is-right.is-hoverable
            .dropdown-trigger
              button.button[aria-haspopup='true' aria-controls='dropdown-menu']
                span= t('misc.operation')
                span.icon.is-small
                  i.fa.fa-angle-down[aria-hidden='true']
            .dropdown-menu[role='menu']
              .dropdown-content
                - if can? :edit, @faq_category
                  = link_to t('misc.edit'), edit_faq_category_path(faq_category), class: 'dropdown-item'
                - if can? :destroy, @faq_category
                  = link_to t('misc.destroy'), faq_category_path(faq_category), class: 'dropdown-item',
                            method: :delete, data: { confirm: '本当に削除しますか？' }

.section
  .field.is-pulled-right
    = page_entries_info @faq_categories
.section
  .field.is-pulled-right
    = paginate @faq_categories

app/views/faq_categories/_search_form.html.slim
nav.panel
  .panel-heading= t('misc.search')
  .panel-block
    = search_form_for(@q, url: faq_categories_path, class: 'control') do |f|
      .field.is-horizontal
        .field-label= f.label :category, FaqCategory.human_attribute_name(:category), class: 'label'
        .field-body
          .field
            p.control= f.text_field :category_cont, class: 'input'

      .field.is-horizontal
        .field-label
        .field-body
          .field
            p.control.is-pulled-right= f.submit t('misc.search'), class: 'button is-info'

app/views/faq_categories/edit.html.slim
h2.title #{FaqCategory.model_name.human}#{t('misc.edit')}
= render 'form'

app/views/faq_categories/index.html.slim
h2.title #{FaqCategory.model_name.human}#{t('misc.index')}
- if can? :new, @faq_category
  = render 'search_form'
  .control-box.field.is-pulled-left
    = link_to "#{FaqCategory.model_name.human}#{t('misc.new')}", new_faq_category_path, class: 'button is-primary'
- if can? :new, @question
  .dropdown.is-right.is-hoverable.is-pulled-right
    .dropdown-trigger
    button.button[aria-haspopup='true' aria-controls='dropdown-menu']
      span= Question.model_name.human
      span.icon.is-small
        i.fa.fa-angle-down[aria-hidden='true']
    .dropdown-menu[role='menu']
      .dropdown-content
        = link_to t('misc.index'), questions_path, class: 'dropdown-item'
        = link_to t('misc.new'), new_question_path, class: 'dropdown-item'

- if @faq_categories.size.zero?
  .title.is-5= t('message.info.none_results')
- else
  = render 'results'

app/views/faq_categories/new.html.slim
h2.title #{FaqCategory.model_name.human}#{t('misc.new')}
= render 'form'