config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount_roboto
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  root 'pages#home'

  resources :users do
    member do
      patch 'activate'
      patch 'suspend'
    end
  end

  resources :posts
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :posts, only: %i[index]
    end
    namespace :api, default: { format: :json } do
      resources :posts
    end
  end

  resources :about_items, only: %i[index new edit create update destroy] do
    member do
      patch 'move_first'
      patch 'move_previous'
      patch 'move_next'
      patch 'move_last'
    end
  end
  get 'about', to: 'about_items#index'

  resources :histories, param: :generation_code do
    resources :activities, only: %i[index new edit create update destroy]
    resources :upload_files, only: %i[index new edit create update destroy] do
      member do
        post 'download'
      end
    end
  end

  resources :supporters, only: %i[index new edit create update destroy] do
    member do
      patch 'move_first'
      patch 'move_previous'
      patch 'move_next'
      patch 'move_last'
    end
  end

  resources :questions, only: %i[index new edit create update destroy]
  get 'faq', to: 'questions#index'

  resources :faq_categories, only: %i[index new edit create update destroy]

  resources :contacts, only: %i[new create]
  get 'contact', to: 'contacts#new'

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/models/history.rb
# == Schema Information
#
# Table name: histories
#
#  id              :bigint(8)        not null, primary key
#  generation_name :string(255)
#  image           :string(255)
#  description     :text(65535)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  generation_code :string(255)
#  image_tmp       :string(255)
#

class History < ApplicationRecord
  has_many :activities, dependent: :destroy
  has_many :upload_files, dependent: :destroy
  validates :generation_code, presence: true, uniqueness: true
  validates :generation_name, presence: true
  mount_uploader :image, ImageUploader
  # store_in_background :image if Rails.env.production?
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  before_action :set_history, only: %i[show edit destroy]
  load_and_authorize_resource
  add_breadcrumb "#{History.model_name.human}#{I18n.t('misc.index')}", :histories_path
  # GET /histories
  def index
    @q = History.all.ransack(params[:q])
    @histories = @q.result.page(params[:page])
  end

  # GET /histories/:generation_code
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/:generation_code/edit
  def edit
  end

  # POST /histories
  def create
    @history = History.new(history_params)
    if @history.errors.empty? && @history.save
      redirect_to histories_path, notice: I18n.t('activerecord.flash.history.actions.create.success')
    else
      render :new, alert: I18n.t('activerecord.flash.history.actions.create.failure')
    end
  end

  # PATCH/PUT /histories/:generation_code
  def update
    @history = History.find_by(id: params[:generation_code])
    if @history.errors.empty? && @history.update(history_params)
      redirect_to histories_path, notice: I18n.t('activerecord.flash.history.actions.update.success')
    else
      render :edit, alert: I18n.t('activerecord.flash.history.actions.update.failure')
    end
  end

  # DELETE /histories/:generation_code
  def destroy
    if @history.destroy
      redirect_to histories_path, notice: I18n.t('activerecord.flash.history.actions.destroy.success')
    else
      redirect_to histories_path, alert: I18n.t('activerecord.flash.history.actions.destroy.failure')
    end
  end

  private

  def set_history
    @history = History.find_by(generation_code: params[:generation_code])
  end

  def history_params
    params.require(:history).permit(:generation_code, :generation_name, :image, :remove_image, :image_cache, :description, :file, :file_type)
  end
end

app/views/histories/_form.html.slim
.has-text-centered
  .column.is-4.is-offset-4
    - if @history.errors.any?
      - @history.errors.full_messages.each do |message|
        .notification.is-danger
          = message

= form_with(model: @history, local: true, class: 'control') do |f|
  .field.is-horizontal
    .field-label= f.label :generation_name, class: 'label'
    .field-body
      .field
        p.control= f.text_field :generation_name, class: 'input'

  .field.is-horizontal
    .field-label= f.label :generation_code, class: 'label', require: true
    .field-body
      .field
        p.control= f.text_field :generation_code, class: 'input'

  .field.is-horizontal
    .field-label= f.label :image, class: 'label'
    .field-body
      .field
        - if @history.image.present?
          b.control= '現在選択されている画像：' + File.basename(@history.image.to_s)
          p.control= image_tag @history.image_url(:thumb)
          b.control= f.label '↓画像を削除する', class: 'label'
          p.control= f.check_box :remove_image, class: 'checkbox'
        p.control= f.file_field :image, class: 'input'
        p.control= f.hidden_field :image_cache

  .field.is-horizontal
    .field-label= f.label :description, class: 'label'
    .field-body
      .field
        p.control= f.text_area :description, class: 'textarea'

  .field.is-horizontal
    .field-label
    .field-body
      .field
        .control.is-pulled-right= f.submit nil, class: 'button is-primary'

app/views/histories/_part_result.html.slim
- if can? :new, @activity
  .control-box.field.is-pulled-left
    = link_to "#{Activity.model_name.human}#{t('misc.new')}", new_history_activity_path(@history.generation_code), class: 'button is-primary'

.field.is-grouped.is-pulled-left
  p.control
    .button
      span.icon.fa.fa-download
      span= link_to "#{UploadFile.model_name.human}#{I18n.t('misc.download')}", history_upload_files_path(@history, @upload_files)

- @history.activities.each do |activity|
  - if current_user.present? && current_user.admin?
    .dropdown.is-right.is-hoverable.is-pulled-right[style='margin-top: 100px;']
      .dropdown-trigger
      button.button[aria-haspopup='true' aria-controls='dropdown-menu']
        span= t('misc.operation')
        span.icon.is-small
          i.fa.fa-angle-down[aria-hidden='true']
      .dropdown-menu[role='menu']
        .dropdown-content
          - if can? :edit, @activity
            = link_to t('misc.edit'), edit_history_activity_path(@history, activity), class: 'dropdown-item'
          - if can? :destroy, @activity
            = link_to t('misc.destroy'), history_activity_path(@history, activity), class: 'dropdown-item',
                      method: :delete, data: { confirm: '本当に削除しますか？' }
  .columns.has-text-centered[style='margin-top: 100px;']
    .column.is-full-width
      .title= activity.title
    .column.is-full-width
      p= activity.content

app/views/histories/_results.html.slim
.section
  .field.is-pulled-right
    = page_entries_info @histories
.section
  .field.is-pulled-right
    = paginate @histories

table.table.is-fullwidth.is-striped
  thead
    tr
      th= History.human_attribute_name :image
      th= History.human_attribute_name :generation_name
      th= History.human_attribute_name :description
      th

  tbody
    - @histories.each do |history|
      tr
        td
          - if history.image.present?
            = image_tag history.image_url(:thumb)
        td= history.generation_name
        td= history.description
        td
          .dropdown.is-right.is-hoverable
            .dropdown-trigger
              button.button[aria-haspopup='true' aria-controls='dropdown-menu']
                span= t('misc.operation')
                span.icon.is-small
                  i.fa.fa-angle-down[aria-hidden='true']
            .dropdown-menu[role='menu']
              .dropdown-content
                = link_to t('misc.show'), history_path(history.generation_code), class: 'dropdown-item'
                - if can? :edit, @history
                  = link_to t('misc.edit'), edit_history_path(history.generation_code), class: 'dropdown-item'
                - if can? :destroy, @history
                  = link_to t('misc.destroy'), history_path(history.generation_code), class: 'dropdown-item',
                            method: :delete, data: { confirm: '本当に削除しますか？' }

.section
  .field.is-pulled-right
    = page_entries_info @histories
.section
  .field.is-pulled-right
    = paginate @histories

app/views/histories/_search_form.html.slim
nav.panel
  .panel-heading= t('misc.search')
  .panel-block
    = search_form_for(@q, url: histories_path, class: 'control') do |f|
      .field.is-horizontal
        .field-label= f.label :generation_name, History.human_attribute_name(:generation_name), class: 'label'
        .field-body
          .field
            p.control= f.text_field :generation_name_cont, class: 'input'

      .field.is-horizontal
        .field-label
        .field-body
          .field
            p.control.is-pulled-right= f.submit t('misc.search'), class: 'button is-info'

app/views/histories/edit.html.slim
h2.title #{History.model_name.human}#{t('misc.edit')}
= render 'form'

app/views/histories/index.html.slim
h2.title #{History.model_name.human}#{t('misc.index')}
- if can? :new, @history
  = render 'search_form'
  .control-box.field.is-pulled-left
    = link_to "#{History.model_name.human}#{t('misc.new')}", new_history_path, class: 'button is-primary'

- if @histories.size.zero?
  .title.is-5= t('message.info.none_results')
- else
  = render 'results'

app/views/histories/new.html.slim
h2.title #{History.model_name.human}#{t('misc.new')}
= render 'form'

app/views/histories/show.html.slim
h2.title #{History.model_name.human}#{t('misc.show')}
= render 'part_result'