config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount_roboto
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  root 'pages#home'

  resources :users do
    member do
      patch 'activate'
      patch 'suspend'
    end
  end

  resources :posts
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :posts, only: %i[index]
    end
    namespace :api, default: { format: :json } do
      resources :posts
    end
  end

  resources :about_items, only: %i[index new edit create update destroy] do
    member do
      patch 'move_first'
      patch 'move_previous'
      patch 'move_next'
      patch 'move_last'
    end
  end
  get 'about', to: 'about_items#index'

  resources :histories, param: :generation_code do
    resources :activities, only: %i[index new edit create update destroy]
    resources :upload_files, only: %i[index new edit create update destroy] do
      member do
        post 'download'
      end
    end
  end

  resources :supporters, only: %i[index new edit create update destroy] do
    member do
      patch 'move_first'
      patch 'move_previous'
      patch 'move_next'
      patch 'move_last'
    end
  end

  resources :questions, only: %i[index new edit create update destroy]
  get 'faq', to: 'questions#index'

  resources :faq_categories, only: %i[index new edit create update destroy]

  resources :contacts, only: %i[new create]
  get 'contact', to: 'contacts#new'

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/models/about_item.rb
# == Schema Information
#
# Table name: about_items
#
#  id          :bigint(8)        not null, primary key
#  sort_rank   :integer
#  image       :string(255)
#  description :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image_tmp   :string(255)
#

class AboutItem < ApplicationRecord
  validates :sort_rank, presence: true, uniqueness: true,
                        numericality: { only_integer: true, greater_than: 0 }

  mount_uploader :image, ImageUploader
  # store_in_background :image if Rails.env.production?
end

app/controllers/about_items_controller.rb
class AboutItemsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  before_action :set_about_item, only: %i[edit update destroy move_first move_previous move_next move_last]
  load_and_authorize_resource
  # GET /about
  def index
    @about_items = AboutItem.all.order(sort_rank: :asc)
  end

  # GET /about_items/new
  def new
    @about_item = AboutItem.new
  end

  # GET /about_items/:id/edit
  def edit
  end

  # POST /about_items
  def create
    @about_item = AboutItem.new(about_item_params)
    if @about_item.errors.empty? && @about_item.save
      redirect_to about_path, notice: I18n.t('activerecord.flash.about_item.actions.create.success')
    else
      render :new, alert: I18n.t('activerecord.flash.about_item.actions.create.failure')
    end
  end

  # PATCH/PUT /about_items/:id
  def update
    if @about_item.errors.empty? && @about_item.update(about_item_params)
      redirect_to about_path, notice: I18n.t('activerecord.flash.about_item.actions.update.success')
    else
      render :edit, alert: I18n.t('activerecord.flash.about_item.actions.update.failure')
    end
  end

  # DELETE /about_items/:id
  def destroy
    if @about_item.destroy
      redirect_to about_path, notice: I18n.t('activerecord.flash.about_item.actions.destroy.success')
    else
      redirect_to about_path, alert: I18n.t('activerecord.flash.about_item.actions.destroy.failure')
    end
  end

  def move_first
    first_about_item = AboutItem.find_by(sort_rank: 1)
    second_about_item = AboutItem.find_by(sort_rank: 2)
    if first_about_item.present? && second_about_item.present?
      remaining_about_items = AboutItem.where(['(sort_rank >= ?) AND (sort_rank < ?)', 2, @about_item.sort_rank])
      remaining_about_items.order(sort_rank: :asc).each do |remaining_about_item|
        remaining_about_item.sort_rank += 1
        remaining_about_item.save!(validate: false)
      end
      first_about_item.sort_rank = 2
      first_about_item.save!(validate: false)
    end
    @about_item.sort_rank = 1
    @about_item.save!(validate: false)
    redirect_to about_path, notice: I18n.t('activerecord.flash.about_item.actions.move_first.success')
  end

  def move_previous
    previous_about_item = AboutItem.where('sort_rank < ?', @about_item.sort_rank).order(sort_rank: :desc).first
    if previous_about_item.present?
      @about_item.sort_rank, previous_about_item.sort_rank = previous_about_item.sort_rank, @about_item.sort_rank
      previous_about_item.save!(validate: false)
    else
      @about_item.sort_rank -= 1
    end
    @about_item.save!(validate: false)
    redirect_to about_path, notice: I18n.t('activerecord.flash.about_item.actions.move_previous.success')
  end

  def move_next
    next_about_item = AboutItem.where('sort_rank > ?', @about_item.sort_rank).order(sort_rank: :asc).first
    if next_about_item.present?
      @about_item.sort_rank, next_about_item.sort_rank = next_about_item.sort_rank, @about_item.sort_rank
      next_about_item.save!(validate: false)
    else
      @about_item.sort_rank += 1
    end
    @about_item.save!(validate: false)
    redirect_to about_path, notice: I18n.t('activerecord.flash.about_item.actions.move_next.success')
  end

  def move_last
    last_about_item = AboutItem.order(sort_rank: :asc).last
    last_but_one_about_item = AboutItem.find_by(sort_rank: last_about_item.sort_rank - 1)
    if last_about_item.present? && last_but_one_about_item.present?
      remaining_about_items = AboutItem.where(['(sort_rank > ?) AND (sort_rank <= ?)', @about_item.sort_rank, last_about_item.sort_rank])
      remaining_about_items.order(sort_rank: :asc).each do |remaining_about_item|
        remaining_about_item.sort_rank -= 1
        remaining_about_item.save!(validate: false)
      end
      last_about_item.sort_rank -= 1
      last_about_item.save!(validate: false)
    end
    @about_item.sort_rank = last_about_item.sort_rank + 1
    @about_item.save!(validate: false)
    redirect_to about_path, notice: I18n.t('activerecord.flash.about_item.actions.move_last.success')
  end

  private

  def about_item_params
    params.require(:about_item).permit(:sort_rank, :image, :description, :image_cache, :remove_image)
  end

  def set_about_item
    @about_item = AboutItem.find(params[:id])
  end
end

app/views/about_items/_form.html.slim
.has-text-centered
  .column.is-4.is-offset-4
    - if @about_item.errors.any?
      - @about_item.errors.full_messages.each do |message|
        .notification.is-danger
          = message

= form_with(model: @about_item, local: true, class: 'control') do |f|
  .field.is-horizontal
    .field-label= f.label :sort_rank, class: 'label', require: true
    .field-body
      .field
        p.control= f.number_field :sort_rank, class: 'input'

  .field.is-horizontal
    .field-label= f.label :image, class: 'label'
    .field-body
      .field
        - if @about_item.image.present?
          b.control= '現在選択されている画像：' + File.basename(@about_item.image.to_s)
          p.control= image_tag @about_item.image_url(:thumb)
          b.control= f.label '↓画像を削除する', class: 'label'
          p.control= f.check_box :remove_image, class: 'checkbox'
        p.control= f.file_field :image, class: 'input'
        p.control= f.hidden_field :image_cache

  .field.is-horizontal
    .field-label= f.label :description, class: 'label'
    .field-body
      .field
        p.control= f.text_area :description, class: 'textarea'

  .field.is-horizontal
    .field-label
    .field-body
      .field
        .control.is-pulled-right= f.submit nil, class: 'button is-primary'

app/views/about_items/_results.html.slim
- @about_items.each do |about_item|
  - if current_user.present? && current_user.admin?
    .dropdown.is-right.is-hoverable.is-pulled-right
      .dropdown-trigger
      button.button[aria-haspopup='true' aria-controls='dropdown-menu']
        span= t('misc.operation')
        span.icon.is-small
          i.fa.fa-angle-down[aria-hidden='true']
      .dropdown-menu[role='menu']
        .dropdown-content
          - if can? :manage, @about_item
            = link_to t('misc.edit'), edit_about_item_path(about_item), class: 'dropdown-item'
            = link_to t('misc.destroy'), about_item_path(about_item), class: 'dropdown-item',
                      method: :delete, data: { confirm: '本当に削除しますか？' }
            - unless about_item.sort_rank == 1
              = link_to t('misc.move_first'), move_first_about_item_path(about_item), method: :patch, class: 'dropdown-item'
              = link_to t('misc.move_previous'), move_previous_about_item_path(about_item), method: :patch, class: 'dropdown-item'
            - unless about_item.sort_rank == AboutItem.order(sort_rank: :asc).last.sort_rank
              = link_to t('misc.move_next'), move_next_about_item_path(about_item), method: :patch, class: 'dropdown-item'
              = link_to t('misc.move_last'), move_last_about_item_path(about_item), method: :patch, class: 'dropdown-item'
  .columns
    - if about_item.image.present? && about_item.description.present?
      .column.is-fullwidth-mobile.is-half-desktop
        = image_tag about_item.image_url(:sub)
      .column.is-fullwidth-mobile.is-half-desktop[style='font-size: 1.6rem;']
        = about_item.description
    - elsif about_item.image.blank? && about_item.description.blank?
      = ''
    - else
      .column.is-full-width.has-text-centered[style='font-size: 1.6rem;']
          = image_tag about_item.image_url(:main) if about_item.image.present?
          = about_item.description

app/views/about_items/edit.html.slim
h2.title #{AboutItem.model_name.human}#{t('misc.edit')}
= render 'form'

app/views/about_items/index.html.slim
- set_meta_tags title: t('misc.about'), description: t('misc.about'), og: { title: t('misc.about'), type: 'article', image: '' }
- @page_title = t('misc.about')
h2.title =t('misc.about')
- if can? :new, @about_item
  .control-box.field.is-pulled-left
    = link_to "#{AboutItem.model_name.human}#{t('misc.new')}", new_about_item_path, class: 'button is-primary'
= render 'results'

app/views/about_items/new.html.slim
h2.title #{AboutItem.model_name.human}#{t('misc.new')}
= render 'form'