config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount_roboto
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  root 'pages#home'

  resources :users do
    member do
      patch 'activate'
      patch 'suspend'
    end
  end

  resources :posts
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :posts, only: %i[index]
    end
    namespace :api, default: { format: :json } do
      resources :posts
    end
  end

  resources :about_items, only: %i[index new edit create update destroy] do
    member do
      patch 'move_first'
      patch 'move_previous'
      patch 'move_next'
      patch 'move_last'
    end
  end
  get 'about', to: 'about_items#index'

  resources :histories, param: :generation_code do
    resources :activities, only: %i[index new edit create update destroy]
    resources :upload_files, only: %i[index new edit create update destroy] do
      member do
        post 'download'
      end
    end
  end

  resources :supporters, only: %i[index new edit create update destroy] do
    member do
      patch 'move_first'
      patch 'move_previous'
      patch 'move_next'
      patch 'move_last'
    end
  end

  resources :questions, only: %i[index new edit create update destroy]
  get 'faq', to: 'questions#index'

  resources :faq_categories, only: %i[index new edit create update destroy]

  resources :contacts, only: %i[new create]
  get 'contact', to: 'contacts#new'

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/models/supporter.rb
# == Schema Information
#
# Table name: supporters
#
#  id         :bigint(8)        not null, primary key
#  sort_rank  :integer
#  type       :integer
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  url        :string(255)
#  image_tmp  :string(255)
#

class Supporter < ApplicationRecord
  extend Enumerize
  validates :type, presence: true
  validates :sort_rank, presence: true, uniqueness: { scope: :type },
                        numericality: { only_integer: true, greater_than: 0 }
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  # store_in_background :image if Rails.env.production?
  enumerize :type, in: { kyousann: 0, kouenn: 1, josei: 2 }
  # Not to rename type in ActiveRecord
  self.inheritance_column = :_type_disabled

  class << self
    def kyousann
      where(type: :kyousann)
    end

    def kouenn
      where(type: :kouenn)
    end

    def josei
      where(type: :josei)
    end
  end
end

app/controllers/supporters_controller.rb
class SupportersController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  before_action :set_supporter, only: %i[update destroy move_first move_previous move_next move_last]
  load_and_authorize_resource
  add_breadcrumb "#{Supporter.model_name.human}#{I18n.t('misc.index')}", :supporters_path
  # GET /supporters
  def index
    @supporters = Supporter.all
  end

  # GET /supporters/new
  def new
    @supporter = Supporter.new
  end

  # GET /supporters/:id/edit
  def edit
  end

  # POST /supporters
  def create
    @supporter = Supporter.new(supporter_params)
    if @supporter.errors.empty? && @supporter.save
      redirect_to supporters_path, notice: I18n.t('activerecord.flash.supporter.actions.create.success')
    else
      render :new, alert: I18n.t('activerecord.flash.supporter.actions.create.failure')
    end
  end

  # PATCH/PUT /supporters/:id
  def update
    if @supporter.errors.empty? && @supporter.update(supporter_params)
      redirect_to supporters_path, notice: I18n.t('activerecord.flash.supporter.actions.update.success')
    else
      render :edit, alert: I18n.t('activerecord.flash.supporter.actions.update.failure')
    end
  end

  # DELETE /supporters/:id
  def destroy
    if @supporter.destroy
      redirect_to supporters_path, notice: I18n.t('activerecord.flash.supporter.actions.destroy.success')
    else
      redirect_to supporters_path, alert: I18n.t('activerecord.flash.supporter.actions.destroy.failure')
    end
  end

  def move_first
    first_supporter = Supporter.where(type: @supporter.type).find_by(sort_rank: 1)
    second_supporter = Supporter.where(type: @supporter.type).find_by(sort_rank: 2)
    if first_supporter.present? && second_supporter.present?
      remaining_supporters = Supporter.where(type: @supporter.type).where(['(sort_rank >= ?) AND (sort_rank < ?)', 2, @supporter.sort_rank])
      remaining_supporters.order(sort_rank: :asc).each do |remaining_supporter|
        remaining_supporter.sort_rank += 1
        remaining_supporter.save!(validate: false)
      end
      first_supporter.sort_rank = 2
      first_supporter.save!(validate: false)
    end
    @supporter.sort_rank = 1
    @supporter.save!(validate: false)
    redirect_to supporters_path, notice: I18n.t('activerecord.flash.supporter.actions.move_first.success')
  end

  def move_previous
    previous_supporter = Supporter.where(type: @supporter.type).where('sort_rank < ?', @supporter.sort_rank).order(sort_rank: :desc).first
    if previous_supporter.present?
      @supporter.sort_rank, previous_supporter.sort_rank = previous_supporter.sort_rank, @supporter.sort_rank
      previous_supporter.save!(validate: false)
    else
      @supporter.sort_rank -= 1
    end
    @supporter.save!(validate: false)
    redirect_to supporters_path, notice: I18n.t('activerecord.flash.supporter.actions.move_previous.success')
  end

  def move_next
    next_supporter = Supporter.where(type: @supporter.type).where('sort_rank > ?', @supporter.sort_rank).order(sort_rank: :asc).first
    if next_supporter.present?
      @supporter.sort_rank, next_supporter.sort_rank = next_supporter.sort_rank, @supporter.sort_rank
      next_supporter.save!(validate: false)
    else
      @supporter.sort_rank += 1
    end
    @supporter.save!(validate: false)
    redirect_to supporters_path, notice: I18n.t('activerecord.flash.supporter.actions.move_next.success')
  end

  def move_last
    last_supporter = Supporter.where(type: @supporter.type).order(sort_rank: :asc).last
    last_but_one_supporter = Supporter.where(type: @supporter.type).find_by(sort_rank: last_supporter.sort_rank - 1)
    if last_supporter.present? && last_but_one_supporter.present?
      remaining_supporters = Supporter.where(type: @supporter.type).where(['(sort_rank > ?) AND (sort_rank <= ?)', @supporter.sort_rank, last_supporter.sort_rank])
      remaining_supporters.order(sort_rank: :asc).each do |remaining_supporter|
        remaining_supporter.sort_rank -= 1
        remaining_supporter.save!(validate: false)
      end
      last_supporter.sort_rank -= 1
      last_supporter.save!(validate: false)
    end
    @supporter.sort_rank = last_supporter.sort_rank + 1
    @supporter.save!(validate: false)
    redirect_to supporters_path, notice: I18n.t('activerecord.flash.supporter.actions.move_last.success')
  end

  private

  def supporter_params
    params.require(:supporter).permit(:type, :sort_rank, :image, :image_cache, :remove_image, :url)
  end

  def set_supporter
    @supporter = Supporter.find(params[:id])
  end
end

app/views/supporters/_form.html.slim
.has-text-centered
  .column.is-4.is-offset-4
    - if @supporter.errors.any?
      - @supporter.errors.full_messages.each do |message|
        .notification.is-danger
          = message

= form_with(model: @supporter, local: true, class: 'control') do |f|
  .field.is-horizontal
    .field-label= f.label :type, class: 'label', require: true
    .field-body
      .field
       p.control.select= f.select :type, Supporter.type.options, prompt: true, class: 'input'

  .field.is-horizontal
    .field-label= f.label :sort_rank, class: 'label', require: true
    .field-body
      .field
        p.control= f.number_field :sort_rank, class: 'input'

  .field.is-horizontal
    .field-label= f.label :image, class: 'label'
    .field-body
      .field
        - if @supporter.image.present?
          b.control= '現在選択されている画像：' + File.basename(@supporter.image.to_s)
          p.control= image_tag @supporter.image_url(:thumb)
          b.control= f.label '↓画像を削除する', class: 'label'
          p.control= f.check_box :remove_image, class: 'checkbox'
        p.control= f.file_field :image, class: 'input'
        p.control= f.hidden_field :image_cache

  .field.is-horizontal
    .field-label= f.label :url, class: 'label'
    .field-body
      .field
       p.control= f.text_field :url, class: 'input'

  .field.is-horizontal
    .field-label
    .field-body
      .field
        .control.is-pulled-right= f.submit nil, class: 'button is-primary'

app/views/supporters/_results.html.slim
- if @supporters.find_by(type: :josei).present?
  .title.has-text-centered 助成
  - @supporters.josei.order(sort_rank: :asc).each do |josei_supporter|
    - if josei_supporter.url.present?
      a href="#{josei_supporter.url}" target='_blank'
        = image_tag josei_supporter.image_url(:thumb)
    - else
      = image_tag josei_supporter.image_url(:thumb)
    - if current_user.present? && current_user.admin?
      .dropdown.is-right.is-hoverable.is-pulled-bottom
        .dropdown-trigger
        button.button[aria-haspopup='true' aria-controls='dropdown-menu']
          span= t('misc.operation')
          span.icon.is-small
            i.fa.fa-angle-down[aria-hidden='true']
        .dropdown-menu[role='menu']
          .dropdown-content
            - if can? :manage, @supporter
              = link_to t('misc.edit'), edit_supporter_path(josei_supporter), class: 'dropdown-item'
              = link_to t('misc.destroy'), supporter_path(josei_supporter), class: 'dropdown-item',
                        method: :delete, data: { confirm: '本当に削除しますか？' }
              - unless josei_supporter.sort_rank == 1
                = link_to t('misc.move_first'), move_first_supporter_path(josei_supporter), method: :patch, class: 'dropdown-item'
                = link_to t('misc.move_previous'), move_previous_supporter_path(josei_supporter), method: :patch, class: 'dropdown-item'
              - unless josei_supporter.sort_rank == Supporter.where(type: :josei).order(sort_rank: :asc).last.sort_rank
                = link_to t('misc.move_next'), move_next_supporter_path(josei_supporter), method: :patch, class: 'dropdown-item'
                = link_to t('misc.move_last'), move_last_supporter_path(josei_supporter), method: :patch, class: 'dropdown-item'

- if @supporters.find_by(type: :kouenn).present?
  .title.has-text-centered 後援
  - @supporters.kouenn.order(sort_rank: :asc).each do |kouenn_supporter|
    - if kouenn_supporter.url.present?
      a href="#{kouenn_supporter.url}"
        = image_tag kouenn_supporter.image_url(:thumb)
    - else
      = image_tag kouenn_supporter.image_url(:thumb)
    - if current_user.present? && current_user.admin?
      .dropdown.is-right.is-hoverable.is-pulled-bottom
        .dropdown-trigger
        button.button[aria-haspopup='true' aria-controls='dropdown-menu']
          span= t('misc.operation')
          span.icon.is-small
            i.fa.fa-angle-down[aria-hidden='true']
        .dropdown-menu[role='menu']
          .dropdown-content
            - if can? :manage, @supporter
              = link_to t('misc.edit'), edit_supporter_path(kouenn_supporter), class: 'dropdown-item'
              = link_to t('misc.destroy'), supporter_path(kouenn_supporter), class: 'dropdown-item',
                        method: :delete, data: { confirm: '本当に削除しますか？' }
              - unless kouenn_supporter.sort_rank == 1
                = link_to t('misc.move_first'), move_first_supporter_path(kouenn_supporter), method: :patch, class: 'dropdown-item'
                = link_to t('misc.move_previous'), move_previous_supporter_path(kouenn_supporter), method: :patch, class: 'dropdown-item'
              - unless kouenn_supporter.sort_rank == Supporter.where(type: :kouenn).order(sort_rank: :asc).last.sort_rank
                = link_to t('misc.move_next'), move_next_supporter_path(kouenn_supporter), method: :patch, class: 'dropdown-item'
                = link_to t('misc.move_last'), move_last_supporter_path(kouenn_supporter), method: :patch, class: 'dropdown-item'

- if @supporters.find_by(type: :kyousann).present?
  .title.has-text-centered 協賛
  - @supporters.kyousann.order(sort_rank: :asc).each do |kyousann_supporter|
    - if kyousann_supporter.url.present?
      a href="#{kyousann_supporter.url}" target='_blank'
        = image_tag kyousann_supporter.image_url(:thumb)
    - else
      = image_tag kyousann_supporter.image_url(:thumb)
    - if current_user.present? && current_user.admin?
      .dropdown.is-right.is-hoverable.is-pulled-bottom
        .dropdown-trigger
        button.button[aria-haspopup='true' aria-controls='dropdown-menu']
          span= t('misc.operation')
          span.icon.is-small
            i.fa.fa-angle-down[aria-hidden='true']
        .dropdown-menu[role='menu']
          .dropdown-content
            - if can? :manage, @supporter
              = link_to t('misc.edit'), edit_supporter_path(kyousann_supporter), class: 'dropdown-item'
              = link_to t('misc.destroy'), supporter_path(kyousann_supporter), class: 'dropdown-item',
                        method: :delete, data: { confirm: '本当に削除しますか？' }
              - unless kyousann_supporter.sort_rank == 1
                = link_to t('misc.move_first'), move_first_supporter_path(kyousann_supporter), method: :patch, class: 'dropdown-item'
                = link_to t('misc.move_previous'), move_previous_supporter_path(kyousann_supporter), method: :patch, class: 'dropdown-item'
              - unless kyousann_supporter.sort_rank == Supporter.where(type: :kyousann).order(sort_rank: :asc).last.sort_rank
                = link_to t('misc.move_next'), move_next_supporter_path(kyousann_supporter), method: :patch, class: 'dropdown-item'
                = link_to t('misc.move_last'), move_last_supporter_path(kyousann_supporter), method: :patch, class: 'dropdown-item'

app/views/supporters/edit.html.slim
h2.title #{Supporter.model_name.human}#{t('misc.edit')}
= render 'form'

app/views/supporters/index.html.slim
h2.title #{Supporter.model_name.human}#{t('misc.index')}
- if can? :new, @supporter
  .control-box.field.is-pulled-left
    = link_to "#{Supporter.model_name.human}#{t('misc.new')}", new_supporter_path, class: 'button is-primary'

- if @supporters.size.zero?
  .title.is-5= t('message.info.none_results')
- else
  = render 'results'

app/views/supporters/new.html.slim
h2.title #{Supporter.model_name.human}#{t('misc.new')}
= render 'form'